---
- name: Update apt-get repo and cache
  apt: update_cache=yes force_apt_get=yes cache_valid_time=3600

- name: Installing tools
  apt: >
    name={{ item }}
    state=present
    update_cache=yes
  register: __result
  until: __result != 0
  retries: 10
  with_items:
    - net-tools
    - npm
    - python3
    - python3-pip
