---
- name: reload nginx
  service:
    name: nginx
    state: reloaded

- name: restart gitlab
  command: gitlab-ctl reconfigure
  register: gitlab_restart
  failed_when: gitlab_restart_handler_failed_when | bool