---
- name: Download and run script
  shell: sudo curl -L "https://packages.gitlab.com/install/repositories/runner/gitlab-runner/script.deb.sh" | sudo bash

- name: Install runner
  shell: sudo apt-get install gitlab-runner

- name: Set SUDOERS for gitlab-runner
  ansible.builtin.lineinfile:
    path: /etc/sudoers
    insertafter: "^root*"
    line: "gitlab-runner ALL=(ALL:ALL) ALL"

- name: Set SUDOERS for gitlab-runner (NO PASS)
  ansible.builtin.lineinfile:
    path: /etc/sudoers
    line: "gitlab-runner ALL=(ALL) NOPASSWD: ALL"

- name: Set
  command: sudo gitlab-runner register -n --url http://gitlab --registration-token $ecreTT0keN --executor shell
