---
- name: mariadb | systemctl restart mariadb.service
  ansible.builtin.service:
    name: "mariadb.service"
    state: "restarted"
    enabled: true
  loop: "{{ ansible_play_hosts }}"
#  delegate_to: "{{ item }}"
  run_once: true
  changed_when: false
  failed_when: false
