global:
  resolve_timeout: 5m

route:
  group_wait: 10s
  group_interval: 10s
  repeat_interval: 30m

  receiver: "email_notifications"

receivers:
  - name: "email_notifications"
    email_configs:
      - to: n.zastavnuy@gmail.com
        from: test.alertmanager.2022@gmail.com
        smarthost: smtp.gmail.com:587
        auth_username: test.alertmanager.2022@gmail.com
        auth_identity: test.alertmanager.2022@gmail.com
        auth_password: `1qazxsw2
        auth_resolved: true

inhibit_rules:
  - source_match:
      severity: 'critical'
    target_match:
      severity: 'warning'
    equal: ['alertname', 'dev', 'instance']