resource "local_file" "inventory" {
  content = <<-DOC
    # Ansible inventory containing variable values from Terraform.
    # Generated by Terraform.

    [proxy]
    mymind.su ansible_host=${yandex_compute_instance.nat-instance.network_interface.0.nat_ip_address} ansible_user=ubuntu

    [db01]
    db01.mymind.su ansible_host=${yandex_compute_instance.db[0].network_interface.0.ip_address}

    [db01:vars]
    ansible_user=ubuntu
    ansible_ssh_common_args="-o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null -J ubuntu@${yandex_compute_instance.nat-instance.network_interface.0.nat_ip_address}"

    [db02]
    db02.mymind.su ansible_host=${yandex_compute_instance.db[1].network_interface.0.ip_address}

    [db02:vars]
    ansible_user=ubuntu
    ansible_ssh_common_args="-o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null -J ubuntu@${yandex_compute_instance.nat-instance.network_interface.0.nat_ip_address}"

    [app]
    app.mymind.su ansible_host=${yandex_compute_instance.app.network_interface.0.ip_address}

    [app:vars]
    ansible_user=ubuntu
    ansible_ssh_common_args="-o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null -J ubuntu@${yandex_compute_instance.nat-instance.network_interface.0.nat_ip_address}"

    [gitlab]
    gitlab.mymind.su ansible_host=${yandex_compute_instance.gitlab.network_interface.0.ip_address}

    [gitlab:vars]
    ansible_user=ubuntu
    ansible_ssh_common_args="-o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null -J ubuntu@${yandex_compute_instance.nat-instance.network_interface.0.nat_ip_address}"

    [runner]
    runner.mymind.su ansible_host=${yandex_compute_instance.runner.network_interface.0.ip_address}

    [runner:vars]
    ansible_user=ubuntu
    ansible_ssh_common_args="-o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null -J ubuntu@${yandex_compute_instance.nat-instance.network_interface.0.nat_ip_address}"

    [monitor]
    monitoring.mymind.su ansible_host=${yandex_compute_instance.monitor.network_interface.0.ip_address}

    [monitor:vars]
    ansible_user=ubuntu
    ansible_ssh_common_args="-o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null -J ubuntu@${yandex_compute_instance.nat-instance.network_interface.0.nat_ip_address}"

    DOC

filename = "../ansible/inventory"

  depends_on = [
    yandex_compute_instance.nat-instance,
    yandex_compute_instance.db,
    yandex_compute_instance.app,
    yandex_compute_instance.gitlab,
    yandex_compute_instance.runner,
    yandex_compute_instance.monitor
  ]
}



