---
- name: Allow TCP Ports
  iptables:
    chain: INPUT
    rule_num: '1'
    action: insert
    protocol: tcp
    jump: ACCEPT
    destination_port: '3000'

- name: Import Grafana Apt Key
  apt_key:
    url: https://packages.grafana.com/gpg.key
    state: present

- name: Add APT Repository
  apt_repository:
    repo: deb https://packages.grafana.com/oss/deb stable main
    state: present

- name: Install Grafana
  apt:
    name: grafana
    state: present

- name: Start Grafana services
  ansible.builtin.service:
    name: grafana-server
    state: started

- name: wait for service up
  uri:
    url: "http://localhost:3000"
    status_code: 200
  register: __result
  until: __result.status == 200
  retries: 120
  delay: 2

- name: change admin user
  lineinfile:
    path: /etc/grafana/grafana.ini
    regexp: "^;admin_user = admin"
    line: "admin_user = {{ grafana_admin_user }}"

- name: change admin pass
  lineinfile:
    path: /etc/grafana/grafana.ini
    regexp: "^;admin_password = admin"
    line: "admin_password = {{ grafana_admin_pass }}"

- name: disabled initial admin creation
  lineinfile:
    path: /etc/grafana/grafana.ini
    regexp: "^;disable_initial_admin_creation = true"
    line: "disable_initial_admin_creation = false"

#- name: Copy Datasource for Grafana
#  grafana_datasource:
#    name: "prometheus-local"
#    grafana_url: "http://192.168.20.60:3000"
#    grafana_user: "{{ grafana_admin_user }}"
#    grafana_password: "{{ grafana_admin_pass }}"
#    org_id: "1"
#    ds_type: "prometheus"
#    ds_url: "http://192.168.20.60:9090"
#  changed_when: false

- name: Copy Dashboards for Grafana
  grafana_dashboard:
    grafana_url: "http://192.168.20.60:3000"
    grafana_user: "admin"
    grafana_password: "admin"
    org_id: 1
    state: export
    uid: "8010"
    path: "/var/lib/grafana/8010.json"
  tags: grafcopy

- name: Activate Dashboards for Node Exporter
  template:
    src: dashboard-node-exporter.yml.j2
    dest: /etc/grafana/provisioning/dashboards/dashboard-node-exporter.yml
    mode: 0755
  notify:
    - grafana systemd
