---
- name: Installing tools
  apt: >
    name={{ item }}
    state=present
    update_cache=yes
  with_items:
    - nginx
    - php8.1
    - php8.1-cgi
    - php8.1-fpm
    - php8.1-mysql
    - php8.1-curl

- name: Replace nginx.conf
  template:
    src: templates/nginx.conf
    dest: /etc/nginx/nginx.conf
    mode: 0644
    owner: root
    group: root
  tags: test

- name: Disable default site
  file:
    path: /var/www/html
    state: absent

- name: Disable settings server nginx
  file:
    path: /etc/nginx/sites-enabled/default
    state: absent

- name: Disable settings server nginx
  file:
    path: /etc/nginx/sites-available/default
    state: absent

- name: Create home directory for www
  file:
    path: /var/www/{{ inventory_hostname }}
    state: directory
    mode: 0664
    owner: www-data
    group: www-data

- name: Add virtual domain
  vars:
    fastcgi_pass_path: /var/run/php/php8.1-fpm.sock
  block:
    - name: set config
      template:
        src: templates/nginx_vhosts.conf
        dest: /etc/nginx/sites-available/{{ inventory_hostname }}.conf
        backup: true
        mode: 0755
    - name: set link
      file:
        src: /etc/nginx/sites-available/{{ inventory_hostname }}.conf
        dest: /etc/nginx/sites-enabled/{{ inventory_hostname }}.conf
        owner: root
        group: root
        state: link
