# For more information, see: https://docs.gitlab.com/ee/ci/yaml/index.html#stages
# https://gitlab.com/gitlab-org/gitlab/-/blob/master/lib/gitlab/ci/templates/Getting-Started.gitlab-ci.yml

# added variables in Settings >> CI/CD >> Variables:
  # SSH_PRIVATE_KEY
  # SSH_KNOWN_HOSTS

before_script:
  # - echo "$SSH_KNOWN_HOSTS" >> ~/.ssh/known_hosts
  # - chmod 644 ~/.ssh/known_hosts
  - 'which ssh-agent || ( apt-get update -y && apt-get install openssh-client git -y )'
  - eval $(ssh-agent -s)
  - mkdir -p ~/.ssh
  - chmod 700 ~/.ssh
  - echo 'echo "$SSH_PASSPHRASE"' > ~/.ssh/.print_ssh_password
  - chmod 700 ~/.ssh/.print_ssh_password
  - chmod +x ~/.ssh/.print_ssh_password
  - echo "$SSH_PRIVATE_KEY" | tr -d '\r' | DISPLAY=":0.0" SSH_ASKPASS=~/.ssh/.print_ssh_password setsid ssh-add - > /dev/null

stages:          # List of stages for jobs, and their order of execution
  - deploy

deploy-job:      # This job runs in the deploy stage.
  stage: deploy  # It only runs when *both* jobs in the test stage complete successfully.
  environment: production
  script:
    - echo "Deploying application..."

    - ssh -o StrictHostKeyChecking=no ubuntu@192.168.20.30 sudo chown ubuntu /var/www/app.mymind.su/ -R
    - rsync -arvzc -e "ssh -o StrictHostKeyChecking=no" ./* ubuntu@192.168.20.30:/var/www/app.mymind.su/
    - ssh -o StrictHostKeyChecking=no ubuntu@192.168.20.30 sudo chown www-data /var/www/app.mymind.su/ -R 