---
- name: Install Nginx Web Server on Ubuntu
  apt:
    name:
      - nginx
      - ssl-cert
      - snapd
    state: present
    update_cache: yes
  register: nginxinstalled
  delay: 10
  retries: 12
  until: nginxinstalled is successful
  notify: Start Nginx
  tags: snapd

- name: Disable default site
  file:
    path: /var/www/html
    state: absent

- name: Disable settings server nginx
  file:
    path: /etc/nginx/sites-enabled/default
    state: absent

- name: Disable settings server nginx
  file:
    path: /etc/nginx/sites-available/default
    state: absent

- name: Replace nginx.conf
  template:
    src=templates/nginx.conf
    dest=/etc/nginx/nginx.conf

- name: Add virtual domain in Revers Proxy
  vars:
    fastcgi_pass_path: /run/php/php8.1-fpm.sock
  block:
    - name: set config
      template:
        src: templates/nginx_vhosts.conf
        dest: /etc/nginx/sites-available/{{ inventory_hostname }}.conf
        backup: true
        mode: 0755
    - name: set link
      file:
        src: /etc/nginx/sites-available/{{ inventory_hostname }}.conf
        dest: /etc/nginx/sites-enabled/{{ inventory_hostname }}.conf
        owner: root
        group: root
        state: link
  notify:
    - Nginx restart
  tags: proxy add

- name: Install Certbot
  shell: "sudo snap install --classic certbot"


- name: Set link from Certbot
  file:
    src: "/snap/bin/certbot"
    path: "/usr/bin/certbot"
    state: link

- name: Install letsencrypt certificates
  command:
    cmd: "sudo certbot --nginx --noninteractive --agree-tos --email n.zastavnuy@gmail.com -d {{ item }}"
  loop:
    - "www.mymind.su"
    - "gitlab.mymind.su"
    - "alertmanager.mymind.su"
    - "grafana.mymind.su"
    - "prometheus.mymind.su"
  notify:
    - Nginx restart